# Generated by Django 4.2.7 on 2025-08-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimTrainer",
            fields=[
                (
                    "trainer_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("trainer_name", models.CharField(max_length=255)),
                (
                    "trainer_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DimType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FactPokemon",
            fields=[
                ("pokemon_id", models.AutoField(primary_key=True, serialize=False)),
                ("pokemon_name", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                ("hp", models.IntegerField()),
                ("atk", models.IntegerField()),
                ("def_stat", models.IntegerField()),
                ("atk_spe", models.IntegerField()),
                ("def_spe", models.IntegerField()),
                ("spd", models.IntegerField()),
                (
                    "pokemon_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.factpokemon",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.dimtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonTrainers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.factpokemon",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.dimtrainer",
                    ),
                ),
            ],
        ),
    ]
